import { MigrationInterface, QueryRunner } from "typeorm";

export class MigrationInit1694202192006 implements MigrationInterface {
    name = 'MigrationInit1694202192006'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`staff_team\` DROP FOREIGN KEY \`FK_6e23d5da7bd3fab60b74c3a8ab0\``);
        await queryRunner.query(`ALTER TABLE \`staff_team\` DROP FOREIGN KEY \`FK_a286a701e594982ab8315503147\``);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP FOREIGN KEY \`FK_687c560d38e4336d975c156c3ce\``);
        await queryRunner.query(`ALTER TABLE \`project_staff\` DROP FOREIGN KEY \`FK_a6ebc5f06096cd5544b4cb4b9b0\``);
        await queryRunner.query(`ALTER TABLE \`project_staff\` DROP FOREIGN KEY \`FK_b58f9306295fb4023fd6f0220bd\``);
        await queryRunner.query(`ALTER TABLE \`project_staff\` DROP FOREIGN KEY \`FK_b9bf22f951531ca046cd9e0350e\``);
        await queryRunner.query(`ALTER TABLE \`spent\` DROP FOREIGN KEY \`FK_c5064c08ead09071a08f4e13e6f\``);
        await queryRunner.query(`ALTER TABLE \`project\` DROP FOREIGN KEY \`FK_5f5c6c2ef0b9aa874f6767e32bd\``);
        await queryRunner.query(`ALTER TABLE \`project\` DROP FOREIGN KEY \`FK_b76640329fa79f0b0e9d031c35b\``);
        await queryRunner.query(`ALTER TABLE \`stage\` DROP FOREIGN KEY \`FK_0760bfbac90003c4016470651e0\``);
        await queryRunner.query(`ALTER TABLE \`requirement\` DROP FOREIGN KEY \`FK_8cb242b2f40ef5e238f69a24a04\``);
        await queryRunner.query(`ALTER TABLE \`activity\` DROP FOREIGN KEY \`FK_36726f43f50ebc79f774c4e16e1\``);
        await queryRunner.query(`ALTER TABLE \`activity\` DROP FOREIGN KEY \`FK_4fc1e5b2215f55983bd6013c8e5\``);
        await queryRunner.query(`ALTER TABLE \`staff\` CHANGE \`typeStaffId\` \`id_typestaff\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`spent\` CHANGE \`projectId\` \`id_project\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`stage\` CHANGE \`projectId\` \`id_project\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`requirement\` CHANGE \`stageId\` \`id_stage\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`staff_team\` DROP COLUMN \`staffId\``);
        await queryRunner.query(`ALTER TABLE \`staff_team\` DROP COLUMN \`teamId\``);
        await queryRunner.query(`ALTER TABLE \`project_staff\` DROP COLUMN \`staffId\``);
        await queryRunner.query(`ALTER TABLE \`project_staff\` DROP COLUMN \`projectId\``);
        await queryRunner.query(`ALTER TABLE \`project_staff\` DROP COLUMN \`customerId\``);
        await queryRunner.query(`ALTER TABLE \`project\` DROP COLUMN \`customerId\``);
        await queryRunner.query(`ALTER TABLE \`project\` DROP COLUMN \`typeServiceId\``);
        await queryRunner.query(`ALTER TABLE \`activity\` DROP COLUMN \`requirementId\``);
        await queryRunner.query(`ALTER TABLE \`activity\` DROP COLUMN \`staffId\``);
        await queryRunner.query(`ALTER TABLE \`staff_team\` ADD \`id_staff\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`staff_team\` ADD \`id_team\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`project_staff\` ADD \`id_staff\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`project_staff\` ADD \`id_project\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`project\` ADD \`id_customer\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`project\` ADD \`id_typeservice\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`activity\` ADD \`id_requirement\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`activity\` ADD \`id_staff\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`customer\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`typeservice\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`area\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`charge\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`typestaff\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`team\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`staff_team\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP FOREIGN KEY \`FK_9cbabed01adf56e6dff86bc65e2\``);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP FOREIGN KEY \`FK_5e6a2ce15d9185e3dbbf0eb80c8\``);
        await queryRunner.query(`ALTER TABLE \`staff\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`staff\` CHANGE \`id_area\` \`id_area\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`staff\` CHANGE \`id_charge\` \`id_charge\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`staff\` CHANGE \`id_typestaff\` \`id_typestaff\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`project_staff\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`spent\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`spent\` CHANGE \`id_project\` \`id_project\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`project\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`stage\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`stage\` CHANGE \`id_project\` \`id_project\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`requirement\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`requirement\` CHANGE \`id_stage\` \`id_stage\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`activity\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP FOREIGN KEY \`FK_37d011e0db2a7a4354e5b757fcc\``);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`DROP INDEX \`IDX_a62473490b3e4578fd683235c5\` ON \`user\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`login\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`login\` varchar(40) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD UNIQUE INDEX \`IDX_a62473490b3e4578fd683235c5\` (\`login\`)`);
        await queryRunner.query(`DROP INDEX \`IDX_638bac731294171648258260ff\` ON \`user\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`password\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`password\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD UNIQUE INDEX \`IDX_638bac731294171648258260ff\` (\`password\`)`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`remeber_token\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`remeber_token\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`id_userprofile\` \`id_userprofile\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`userprofile\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`DROP INDEX \`IDX_067411c4909a4f749064497311\` ON \`userprofile\``);
        await queryRunner.query(`ALTER TABLE \`userprofile\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`userprofile\` ADD \`name\` varchar(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`userprofile\` ADD UNIQUE INDEX \`IDX_067411c4909a4f749064497311\` (\`name\`)`);
        await queryRunner.query(`ALTER TABLE \`staff_team\` ADD CONSTRAINT \`FK_ec4fdfa1fd4a0db262c207eadac\` FOREIGN KEY (\`id_staff\`) REFERENCES \`staff\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`staff_team\` ADD CONSTRAINT \`FK_23737ff8dc9bef429909ff80dfc\` FOREIGN KEY (\`id_team\`) REFERENCES \`team\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD CONSTRAINT \`FK_9cbabed01adf56e6dff86bc65e2\` FOREIGN KEY (\`id_area\`) REFERENCES \`area\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD CONSTRAINT \`FK_5e6a2ce15d9185e3dbbf0eb80c8\` FOREIGN KEY (\`id_charge\`) REFERENCES \`charge\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD CONSTRAINT \`FK_27a5043f754e66272669ca6bbb3\` FOREIGN KEY (\`id_typestaff\`) REFERENCES \`typestaff\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`project_staff\` ADD CONSTRAINT \`FK_fa4b8ddcd53e92f1c751d7c9276\` FOREIGN KEY (\`id_staff\`) REFERENCES \`staff\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`project_staff\` ADD CONSTRAINT \`FK_a4c417d517146da4f7c97cbf719\` FOREIGN KEY (\`id_project\`) REFERENCES \`project\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`spent\` ADD CONSTRAINT \`FK_37601fea91a3d66d8b5db36cefc\` FOREIGN KEY (\`id_project\`) REFERENCES \`project\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`project\` ADD CONSTRAINT \`FK_8427cdd00ac82142d7b23c69973\` FOREIGN KEY (\`id_customer\`) REFERENCES \`customer\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`project\` ADD CONSTRAINT \`FK_3b16500a8255e92dc4039b170bd\` FOREIGN KEY (\`id_typeservice\`) REFERENCES \`typeservice\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`stage\` ADD CONSTRAINT \`FK_03f05074f9300ef7e7648f98f85\` FOREIGN KEY (\`id_project\`) REFERENCES \`project\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`requirement\` ADD CONSTRAINT \`FK_8ebd6f76623cff07387568ec5f5\` FOREIGN KEY (\`id_stage\`) REFERENCES \`stage\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`activity\` ADD CONSTRAINT \`FK_890939410e620ac81ac2ac822c1\` FOREIGN KEY (\`id_requirement\`) REFERENCES \`requirement\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`activity\` ADD CONSTRAINT \`FK_f217d7e57a2d5db6d558f007559\` FOREIGN KEY (\`id_staff\`) REFERENCES \`staff\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD CONSTRAINT \`FK_37d011e0db2a7a4354e5b757fcc\` FOREIGN KEY (\`id_userprofile\`) REFERENCES \`userprofile\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`user\` DROP FOREIGN KEY \`FK_37d011e0db2a7a4354e5b757fcc\``);
        await queryRunner.query(`ALTER TABLE \`activity\` DROP FOREIGN KEY \`FK_f217d7e57a2d5db6d558f007559\``);
        await queryRunner.query(`ALTER TABLE \`activity\` DROP FOREIGN KEY \`FK_890939410e620ac81ac2ac822c1\``);
        await queryRunner.query(`ALTER TABLE \`requirement\` DROP FOREIGN KEY \`FK_8ebd6f76623cff07387568ec5f5\``);
        await queryRunner.query(`ALTER TABLE \`stage\` DROP FOREIGN KEY \`FK_03f05074f9300ef7e7648f98f85\``);
        await queryRunner.query(`ALTER TABLE \`project\` DROP FOREIGN KEY \`FK_3b16500a8255e92dc4039b170bd\``);
        await queryRunner.query(`ALTER TABLE \`project\` DROP FOREIGN KEY \`FK_8427cdd00ac82142d7b23c69973\``);
        await queryRunner.query(`ALTER TABLE \`spent\` DROP FOREIGN KEY \`FK_37601fea91a3d66d8b5db36cefc\``);
        await queryRunner.query(`ALTER TABLE \`project_staff\` DROP FOREIGN KEY \`FK_a4c417d517146da4f7c97cbf719\``);
        await queryRunner.query(`ALTER TABLE \`project_staff\` DROP FOREIGN KEY \`FK_fa4b8ddcd53e92f1c751d7c9276\``);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP FOREIGN KEY \`FK_27a5043f754e66272669ca6bbb3\``);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP FOREIGN KEY \`FK_5e6a2ce15d9185e3dbbf0eb80c8\``);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP FOREIGN KEY \`FK_9cbabed01adf56e6dff86bc65e2\``);
        await queryRunner.query(`ALTER TABLE \`staff_team\` DROP FOREIGN KEY \`FK_23737ff8dc9bef429909ff80dfc\``);
        await queryRunner.query(`ALTER TABLE \`staff_team\` DROP FOREIGN KEY \`FK_ec4fdfa1fd4a0db262c207eadac\``);
        await queryRunner.query(`ALTER TABLE \`userprofile\` DROP INDEX \`IDX_067411c4909a4f749064497311\``);
        await queryRunner.query(`ALTER TABLE \`userprofile\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`userprofile\` ADD \`name\` varchar(40) NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_067411c4909a4f749064497311\` ON \`userprofile\` (\`name\`)`);
        await queryRunner.query(`ALTER TABLE \`userprofile\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`id_userprofile\` \`id_userprofile\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`remeber_token\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`remeber_token\` varchar(150) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP INDEX \`IDX_638bac731294171648258260ff\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`password\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`password\` varchar(150) NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_638bac731294171648258260ff\` ON \`user\` (\`password\`)`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP INDEX \`IDX_a62473490b3e4578fd683235c5\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`login\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`login\` varchar(30) NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_a62473490b3e4578fd683235c5\` ON \`user\` (\`login\`)`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD CONSTRAINT \`FK_37d011e0db2a7a4354e5b757fcc\` FOREIGN KEY (\`id_userprofile\`) REFERENCES \`userprofile\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`activity\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`requirement\` CHANGE \`id_stage\` \`id_stage\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`requirement\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`stage\` CHANGE \`id_project\` \`id_project\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`stage\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`project\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`spent\` CHANGE \`id_project\` \`id_project\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`spent\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`project_staff\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`staff\` CHANGE \`id_typestaff\` \`id_typestaff\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`staff\` CHANGE \`id_charge\` \`id_charge\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`staff\` CHANGE \`id_area\` \`id_area\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`staff\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD CONSTRAINT \`FK_5e6a2ce15d9185e3dbbf0eb80c8\` FOREIGN KEY (\`id_charge\`) REFERENCES \`charge\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD CONSTRAINT \`FK_9cbabed01adf56e6dff86bc65e2\` FOREIGN KEY (\`id_area\`) REFERENCES \`area\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`staff_team\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`team\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`typestaff\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`charge\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`area\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`typeservice\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`customer\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`activity\` DROP COLUMN \`id_staff\``);
        await queryRunner.query(`ALTER TABLE \`activity\` DROP COLUMN \`id_requirement\``);
        await queryRunner.query(`ALTER TABLE \`project\` DROP COLUMN \`id_typeservice\``);
        await queryRunner.query(`ALTER TABLE \`project\` DROP COLUMN \`id_customer\``);
        await queryRunner.query(`ALTER TABLE \`project_staff\` DROP COLUMN \`id_project\``);
        await queryRunner.query(`ALTER TABLE \`project_staff\` DROP COLUMN \`id_staff\``);
        await queryRunner.query(`ALTER TABLE \`staff_team\` DROP COLUMN \`id_team\``);
        await queryRunner.query(`ALTER TABLE \`staff_team\` DROP COLUMN \`id_staff\``);
        await queryRunner.query(`ALTER TABLE \`activity\` ADD \`staffId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`activity\` ADD \`requirementId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`project\` ADD \`typeServiceId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`project\` ADD \`customerId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`project_staff\` ADD \`customerId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`project_staff\` ADD \`projectId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`project_staff\` ADD \`staffId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`staff_team\` ADD \`teamId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`staff_team\` ADD \`staffId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`requirement\` CHANGE \`id_stage\` \`stageId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`stage\` CHANGE \`id_project\` \`projectId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`spent\` CHANGE \`id_project\` \`projectId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`staff\` CHANGE \`id_typestaff\` \`typeStaffId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`activity\` ADD CONSTRAINT \`FK_4fc1e5b2215f55983bd6013c8e5\` FOREIGN KEY (\`requirementId\`) REFERENCES \`requirement\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`activity\` ADD CONSTRAINT \`FK_36726f43f50ebc79f774c4e16e1\` FOREIGN KEY (\`staffId\`) REFERENCES \`staff\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`requirement\` ADD CONSTRAINT \`FK_8cb242b2f40ef5e238f69a24a04\` FOREIGN KEY (\`stageId\`) REFERENCES \`stage\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`stage\` ADD CONSTRAINT \`FK_0760bfbac90003c4016470651e0\` FOREIGN KEY (\`projectId\`) REFERENCES \`project\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`project\` ADD CONSTRAINT \`FK_b76640329fa79f0b0e9d031c35b\` FOREIGN KEY (\`customerId\`) REFERENCES \`customer\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`project\` ADD CONSTRAINT \`FK_5f5c6c2ef0b9aa874f6767e32bd\` FOREIGN KEY (\`typeServiceId\`) REFERENCES \`typeservice\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`spent\` ADD CONSTRAINT \`FK_c5064c08ead09071a08f4e13e6f\` FOREIGN KEY (\`projectId\`) REFERENCES \`project\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`project_staff\` ADD CONSTRAINT \`FK_b9bf22f951531ca046cd9e0350e\` FOREIGN KEY (\`staffId\`) REFERENCES \`staff\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`project_staff\` ADD CONSTRAINT \`FK_b58f9306295fb4023fd6f0220bd\` FOREIGN KEY (\`projectId\`) REFERENCES \`project\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`project_staff\` ADD CONSTRAINT \`FK_a6ebc5f06096cd5544b4cb4b9b0\` FOREIGN KEY (\`customerId\`) REFERENCES \`customer\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD CONSTRAINT \`FK_687c560d38e4336d975c156c3ce\` FOREIGN KEY (\`typeStaffId\`) REFERENCES \`typestaff\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`staff_team\` ADD CONSTRAINT \`FK_a286a701e594982ab8315503147\` FOREIGN KEY (\`staffId\`) REFERENCES \`staff\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`staff_team\` ADD CONSTRAINT \`FK_6e23d5da7bd3fab60b74c3a8ab0\` FOREIGN KEY (\`teamId\`) REFERENCES \`team\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
